# This file created by conda-build 3.0.15+56.gd43c51d
# meta.yaml template originally from:
# /Users/rdonnelly/conda/aggregate/conda-feedstock/recipe, last modified Thu Sep 21 17:35:29 2017
# ------------------------------------------------

package:
    name: conda
    version: 4.3.27
source:
    fn: conda-4.3.27.tar.gz
    sha256: 7de3c3fdb9cc0418bed860dd29d03cde211abafdbc236ddeb223b0c253c1dd72
    url: https://github.com/conda/conda/archive/4.3.27.tar.gz
build:
    always_include_files:
        - bin/activate
        - bin/conda
        - bin/deactivate
    entry_points:
        - conda = conda.cli:main
        - conda-env = conda_env.cli.main:main
    number: '0'
    string: py36hb556a21_0
requirements:
    build:
        - asn1crypto 0.22.0 py36hb705621_1
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - cffi 1.10.0 py36h880867e_1
        - chardet 3.0.4 py36h96c241c_1
        - cryptography 2.0.3 py36h22d4226_1
        - idna 2.6 py36h8628d0a_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - pycosat 0.6.2 py36h1486600_0
        - pycparser 2.18 py36h724b2fc_1
        - pyopenssl 17.2.0 py36h5d7bf08_0
        - pysocks 1.6.7 py36hfa33cec_1
        - python 3.6.2 h26d10c0_12
        - readline 7.0 h81b24a6_3
        - requests 2.18.4 py36h4516966_1
        - ruamel_yaml 0.11.14 py36h9d7ade0_2
        - six 1.10.0 py36h1d5bd22_1
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - urllib3 1.22 py36h68b9469_0
        - xz 5.2.3 ha24016e_1
        - yaml 0.1.7 hff548bb_1
        - zlib 1.2.11 h60db283_1
    host:
        - asn1crypto 0.22.0 py36hb705621_1
        - ca-certificates 2017.08.26 ha1e5d58_0
        - certifi 2017.7.27.1 py36hd973bb6_0
        - cffi 1.10.0 py36h880867e_1
        - chardet 3.0.4 py36h96c241c_1
        - cryptography 2.0.3 py36h22d4226_1
        - idna 2.6 py36h8628d0a_1
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - libedit 3.1 hb4e282d_0
        - libffi 3.2.1 hd939716_3
        - ncurses 6.0 ha932d30_1
        - openssl 1.0.2l h57f3a61_2
        - pycosat 0.6.2 py36h1486600_0
        - pycparser 2.18 py36h724b2fc_1
        - pyopenssl 17.2.0 py36h5d7bf08_0
        - pysocks 1.6.7 py36hfa33cec_1
        - python 3.6.2 h26d10c0_12
        - readline 7.0 h81b24a6_3
        - requests 2.18.4 py36h4516966_1
        - ruamel_yaml 0.11.14 py36h9d7ade0_2
        - six 1.10.0 py36h1d5bd22_1
        - sqlite 3.20.1 h900c3b0_1
        - tk 8.6.7 hcdce994_1
        - urllib3 1.22 py36h68b9469_0
        - xz 5.2.3 ha24016e_1
        - yaml 0.1.7 hff548bb_1
        - zlib 1.2.11 h60db283_1
    run:
        - conda-env >=2.6
        - pycosat >=0.6.1
        - pyopenssl >=16.2.0
        - python >=3.6,<3.7.0a0
        - requests >=2.12.4
        - ruamel_yaml >=0.11.14
test:
    commands:
        - python -c "from __future__ import print_function; import conda; print(conda.__version__)"
        - which conda
        - which conda-env
        - conda --version
        - conda info
        - conda env --help
    imports:
        - conda
about:
    description: 'Conda is an open source package management system and environment

        management system for installing multiple versions of software packages

        and their dependencies and switching easily between them. It works on

        Linux, OS X and Windows, and was created for Python programs but can

        package and distribute any software.

        '
    dev_url: https://github.com/conda/conda
    doc_url: http://conda.pydata.org/docs/
    home: http://conda.pydata.org/
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: OS-agnostic, system-level binary package and environment manager.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - kalefranz
        - mcg1969
        - mingwandroid
        - msarahan
        - mwcraig
        - ocefpaf
        - patricksnape
        - pelson
        - scopatz
